import React from 'react'

import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Sections/Header'
import LightMove from '@/components/Decorations/LightMove'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
          {children}
        </main>
        <LightMove />
      </body>
    </html>
  )
}
